service: news-arxiv

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - .git/**
    - .vscode/**
    - .test/**

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  service: "news-arxiv"

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logRetentionInDays: 14
  deploymentBucket:
    name: "autohost-serverless-deployments"
  stackTags:
    service: ${self:custom.service}
    ENV: ${opt:stage, 'dev'}
    Environment: ${opt:stage, 'dev'}
  tags:
    service: ${self:custom.service}
    Environment: ${opt:stage, 'dev'}
  timeout: 900
  memorySize: 256
  versionFunctions: false
  environment:
    ${file(./configs/${self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:getObject
        - s3:putObject
      Resource:
        - "arn:aws:s3:::${file(./configs/${self:provider.stage}.yml):S3_BUCKET}/news-arxiv/*"

layers:
  sdk:
    name: newsarxiv-${self:custom.stage}-aws-sdk
    description: AWS SDK v2 layer for Node.js
    compatibleRuntimes:
      - nodejs20.x
    compatibleArchitectures:
      - arm64
    package:
      artifact: layers/aws-sdk/aws-sdk-layer.zip

functions:
  scanPapers:
    handler: handler.scanPapers
    events:
      # Every day at 9:00 AM UTC
      - schedule: cron(0 9 * * ? *)

# Infrastructure (CloudFormation)
resources:
  Description: "News Arxiv Stack"
